services:
  - type: web
    name: humanoid-robotics-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: COHERE_API_KEY
        value: wF7MQwZNW6it79cGeOmnpiusxydQH5xVjZ8HtxVE
      - key: QDRANT_URL
        value: https://510602b3-7ebe-467e-899c-6bb40a3cafb3.europe-west3-0.gcp.cloud.qdrant.io:6333
      - key: QDRANT_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.muMk_O2xxG4q7o5AWzfSd9w8sJ0uxPKe6cc6XeRcHKE
      - key: QDRANT_COLLECTION
        value: rag_embedding
      - key: AI_PROVIDER
        value: cohere
      - key: EMBEDDING_MODEL
        value: embed-english-v3.0
      - key: CHAT_MODEL
        value: command-r-08-2024
